### PR TITLE
feat: Allow policy authors to write policies that perform image verif…

### PR DESCRIPTION
**Pull request by raulcabello**
Move sigstore verification enums to the sdk

Fix https://github.com/kubewarden/policy-server/issues/99

### CODE REVIEW

**Comment by raulcabello** [comment]
waiting for https://github.com/kubewarden/policy-sdk-rust/pull/32

**Review by viccuad — APPROVED** [review]
Approving. In the case that we go with this approach, I'm happy with this PR.

**Review by jvanz — COMMENTED** [review]
LGTM

**Comment by viccuad** [comment]
Superseded by https://github.com/kubewarden/policy-fetcher/pull/79. @raulcabello closing this for clarity, hope it's ok!

**Pull request closed without merging**
