### PR TITLE
fix: do not use image url to get registry auth data.

### LINKED ISSUE #179: Unable to fetch manifests from private harbor registry
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to verify the signature of a container pulled from a private harbor registry, the following error is returned by the CLI:

``` 
Error from server: error when creating "pull-harbor-success.yaml": admission webhook "clusterwide-verify-image.kubewarden.admission" denied the request: Pod verify-image-valid is not accepted: verification of image harbor.devops.<company>.com/<repo>/<project>:develop failed: Host error: Callback evaluation failure: Cannot fetch manifest of harbor.devops.<company>.com/<repo>/<project>:develop: Not authorized: url https://harbor.devops.<company>.com/v2/<repo>/<project>/manifests/develop
```
and this one by the policy-server log:
``` 
2024-03-15T15:50:38.846810Z ERROR request{method=POST uri=/validate/clusterwide-verify-image?timeout=10s version=HTTP/1.1}:validation{host="policy-server-default-647b6c8c56-lbfq7" policy_id="clusterwide-verify-image" kind="Pod" kind_group="" kind_version="v1" name="verify-image-valid" namespace="test" operation="CREATE" request_uid="d0fa899d-a975-4c47-ac27-16a7a5044c0a" resource="pods" resource_group="" resource_version="v1" subresource=""}:validate{self=PolicyEvaluator { runtime: "wapc" } settings={"modifyImagesWithDigest": Bool(true), "rule": String("PublicKey"), "signatures": Array [Object {"image": String("harbor.devops.<company>.com/<repo>/*"), "pubKeys": Array [String("-----BEGIN PUBLIC KEY-----\n<Public key data>\n-----END PUBLIC KEY-----")]}]}}: policy_evaluator::runtimes::callback: callback evaluation failed policy_id="clusterwide-verify-image" binding="kubewarden" operation="v2/verify" error="Cannot fetch manifest of harbor.devops.<company>.com/<repo>/<project>:develop: Not authorized: url https://harbor.devops.<company>.com/v2/<repo>/<project>/manifests/develop"
2024-03-15T15:50:38.856695Z  INFO request{method=POST uri=/validate/clusterwide-verify-image?timeout=10s version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=81 ms status=200
```

### Expected Behavior

Pull the image and either accept if verified or reject if not verified.

### Steps To Reproduce

1. Generate private/public key pair with cosign
2. sign docker image
3. submit signed image to private harbor registry
4. create robot account for rancher access
6. On rancher, install kubewarden-crds and kubewarden-controller
7. create docker-registry secret in kubewarden namespace referencing robot account from step 4
8. install kubewarden-defaults, modifying helm chart to reference imagePullSecret as in this link: https://docs.kubewarden.io/operator-manual/policy-servers/private-registry
9. install verify-image-signatures policy, set it to use public key used (yaml of latest attempt at solving this on my own in Anything else)
10. Provide harbor secret to namespace you want image in
11. kubectl apply -f pull-harbor-success.yaml (contents in anything else)

### Environment

```markdown
Cosign version: 2.2.3
Harbor version: v2.10.0-6abb4eab
K8s implementation: EKS
cert-manager version: 1.14.2
Kubewarden version info:
 - kubewarden-controller: 2.0.8
 - kubewarden-crds: 1.4.5
 - kubewarden-defaults: 1.9.3
 - policy-server: 1.10.0
 - verify-image-signatures: 0.2.8
Rancher version info: 
 - Rancher: 2.8.2
 - Dashboard: 2.8.0
 - Helm: 2.16.8-rancher2
 - Machine: 0.15.0-rancher106
```

### Anything else?

Policy works when following along with this: https://www.kubewarden.io/blog/2022/05/verifying-image-signatures/
None of the default policies have had this issue.
Mutation setting seems to have no effect.
I've tried generating a robot account on harbor that has all possible permissions to no avail.

`verify-image.yaml`
includes things added by rancher. Timestamp reflects latest attempt at solving, I've been working this issue for the last month or so.
``` 
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    artifacthub/pkg: verify-image-signatures/verify-image-signatures/0.2.8
  creationTimestamp: '2024-03-13T19:34:33Z'
  finalizers:
    - kubewarden
  generation: 1
  managedFields:
    - apiVersion: policies.kubewarden.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:artifacthub/pkg: {}
        f:spec:
          .: {}
          f:backgroundAudit: {}
          f:mode: {}
          f:module: {}
          f:mutating: {}
          f:namespaceSelector:
            .: {}
            f:matchExpressions: {}
          f:policyServer: {}
          f:rules: {}
          f:settings:
            .: {}
            f:modifyImagesWithDigest: {}
            f:rule: {}
            f:signatures: {}
          f:timeoutSeconds: {}
      manager: agent
      operation: Update
      time: '2024-03-13T19:34:33Z'
    - apiVersion: policies.kubewarden.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions:
            .: {}
            k:{"type":"PolicyActive"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PolicyServerConfigurationUpToDate"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PolicyUniquelyReachable"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:mode: {}
          f:policyStatus: {}
      manager: manager
      operation: Update
      subresource: status
      time: '2024-03-15T13:16:53Z'
  name: verify-image
  resourceVersion: '59372597'
  uid: 097ac356-ca34-4073-b648-6e9f49b2a030
spec:
  backgroundAudit: true
  mode: protect
  module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
  mutating: true
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - opa-test
  policyServer: default
  rules:
    - apiGroups:
        - ''
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - pods
  settings:
    modifyImagesWithDigest: true
    rule: PublicKey
    signatures:
      - image: harbor.devops.<company>.com/<repo>/*
        pubKeys:
          - |-
            -----BEGIN PUBLIC KEY-----
            <Public key data>
            -----END PUBLIC KEY-----
  timeoutSeconds: 10
status:
  conditions:
    - lastTransitionTime: '2024-03-15T13:16:53Z'
      message: The policy webhook has been created
      reason: PolicyActive
      status: 'True'
      type: PolicyActive
    - lastTransitionTime: '2024-03-13T19:35:28Z'
      message: The latest replica set is uniquely reachable
      reason: LatestReplicaSetIsUniquelyReachable
      status: 'True'
      type: PolicyUniquelyReachable
    - lastTransitionTime: '2024-03-13T19:34:33Z'
      message: Configuration for this policy is up to date
      reason: ConfigurationVersionMatch
      status: 'True'
      type: PolicyServerConfigurationUpToDate
  mode: protect
  policyStatus: active
  ```
`pull-harbor-success`
```
apiVersion: v1
kind: Pod
metadata:
  name: verify-image-valid
  namespace: test
spec:
  containers:
  - name: test-verify-image
    image: harbor.devops.<company>.com/<repo>/<project>:develop
  imagePullSecrets:
  - name: harbor-regcreds
  ```

### PR DESCRIPTION
**Pull request by jvanz**
## Description

Updates the function used to verify container image signature to use only the registry name to get the auth data from docker config.json file. The current implementation uses the whole container image URL. Which failed to find the relevant auth data falling back to a anonymous authentication. This is a problem with private registries where access credentials must be used.

To fix this problem, this commit extract the registry name from the container image URL and use it to get the auth data from the config.json file.

Fix #179 

## Test

To test this pull request, you can build kwctl using this changes, execute a docker login in the private registry 

1. Generate private/public key pair with cosign
2. Sign docker image
3. Submit signed image to private harbor registry. You can use `demo.goharbor.io`
4. Create robot account in the harbor instance
5. Login into the private registry using the robot account: `docker login ...`
6. Build kwctl using this change
7. `kwctl run --settings-path settings.yaml --request-path pod_creation_signed.json registry://ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8`

**settings.yaml**

```yaml
signatures:
  - image: "PUT YOUR SIGNED CONTAINER IMAGE PREFIX HERE e.g: demo.goharbor.io/testing/*"  
    pubKeys:
      - |
        -----BEGIN PUBLIC KEY-----
       << YOUR COSIGN PUBLIC KEY >>>
        -----END PUBLIC KEY-----

```

 **pod_creation_signed.json**

```json
{
  "uid": "1299d386-525b-4032-98ae-1949f69f9cfc",
  "kind": {
    "group": "",
    "kind": "Pod",
    "version": "v1"
  },
  "resource": {
    "group": "",
    "version": "v1",
    "resource": "pods"
  },
  "object": {
    "metadata": {
      "name": "nginx"
    },
    "spec": {
      "containers": [
        {
          "image": "PUT YOUR SIGNED CONTAINER IMAGE HERE",
          "name": "test-verify-image-signatures"
        }
      ]
    }
  },
  "operation": "CREATE",
  "requestKind": {
    "group": "",
    "version": "v1",
    "kind": "Pod"
  },
  "userInfo": {
    "username": "alice",
    "uid": "alice-uid",
    "groups": [
      "system:authenticated"
    ]
  }
}

```

### CODE REVIEW

**Comment by flavio** [comment]
The change looks good to me, step number 7 is wrong though, because you're pulling the policy from the ghcr, not from a private registry.

It would also be great to extend `kwctl` e2e tests to cover operations done against a private registry. We don't need to start a fancy registry like harbor. This can be done with a vanilla docker-distribution (aka docker registry) configured with some env variable.
You can see how this is done [here](https://github.com/krustlet/oci-distribution/blob/83f7a91d3c27ba1ee5f42043bff0cdadbf4d276f/src/client.rs#L2686-L2704), inside of the unit tests of `oci-distribution`.

**Review by viccuad — APPROVED** [review]
LGTM. I would also like to have a test for it.

**Review by flavio — APPROVED** [review]

**Comment by fabriziosestito** [comment]
> The change looks good to me, step number 7 is wrong though, because you're pulling the policy from the ghcr, not from a private registry.
> 
> It would also be great to extend `kwctl` e2e tests to cover operations done against a private registry. We don't need to start a fancy registry like harbor. This can be done with a vanilla docker-distribution (aka docker registry) configured with some env variable. You can see how this is done [here](https://github.com/krustlet/oci-distribution/blob/83f7a91d3c27ba1ee5f42043bff0cdadbf4d276f/src/client.rs#L2686-L2704), inside of the unit tests of `oci-distribution`.

@flavio @jvanz we already use this in pattern in kwctl e2e tests, see https://github.com/kubewarden/kwctl/blob/1de2f0a7db81e38d4bb5a42cbea059805626b558/tests/e2e.rs#L330

**Comment by jvanz** [comment]
> The change looks good to me, step number 7 is wrong though, because you're pulling the policy from the ghcr, not from a private registry.

It's not wrong. The policy does not need to be in the private registry. We are verifying the container image from the admission request,  `pod_creation_signed.json` in this example

**Pull request merged**
